import type {
  Course,
  DojoTraining,
  OperatorAssignment,
  PlantHierarchy,
} from "../models/lmsTypes";

export const PLANT_HIERARCHY: PlantHierarchy[] = [
  {
    id: "plant-1",
    name: "Plant 1 - Manesar",
    departments: [
      {
        id: "dept-prod",
        name: "Production",
        subDepartments: [
          {
            id: "sub-wire",
            name: "Wiring Harness",
            sections: [
              {
                id: "sec-asm",
                name: "Assembly",
                lines: [
                  {
                    id: "line-3",
                    name: "Line 3",
                    processes: [
                      {
                        id: "proc-conn",
                        name: "Connector Assembly",
                        stations: [
                          {
                            id: "stn-01",
                            name: "Station 01 - Pin Insertion",
                            machines: ["Torque Machine 04", "Manual Jig J-01"],
                          },
                          {
                            id: "stn-02",
                            name: "Station 02 - Housing Lock",
                            machines: ["Locking Press P-02", "Pneumatic Clamp C-01"],
                          },
                        ],
                      },
                      {
                        id: "proc-crimp",
                        name: "Terminal Crimping",
                        stations: [
                          {
                            id: "stn-03",
                            name: "Station 03 - Auto Crimp",
                            machines: ["Automatic Crimper C-12", "Micro-Crimp M-04"],
                          },
                        ],
                      },
                    ],
                  },
                  {
                    id: "line-1",
                    name: "Line 1",
                    processes: [
                      {
                        id: "proc-weld",
                        name: "Ultrasonic Welding",
                        stations: [
                          {
                            id: "stn-04",
                            name: "Station 01 - Splice Weld",
                            machines: ["Ultrasonic Welder U-02", "Sonics S-10"],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              {
                id: "sec-cut",
                name: "Cutting & Stripping",
                lines: [
                  {
                    id: "line-2",
                    name: "Line 2",
                    processes: [
                      {
                        id: "proc-cut",
                        name: "High Speed Wire Cut",
                        stations: [
                          {
                            id: "stn-05",
                            name: "Station 01 - Feeder Cut",
                            machines: ["Komax Alpha 550", "Schleuniger Cut 400"],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            id: "sub-pcb",
            name: "PCB Fabrication",
            sections: [
              {
                id: "sec-smt",
                name: "SMT Section",
                lines: [
                  {
                    id: "line-smt-1",
                    name: "SMT Line 1",
                    processes: [
                      {
                        id: "proc-pick",
                        name: "Component Placement",
                        stations: [
                          {
                            id: "stn-smt-01",
                            name: "Station 01 - Pick & Place",
                            machines: ["Fuji NXT III", "Yamaha YSM20R"],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "dept-qa",
        name: "Quality Control",
        subDepartments: [
          {
            id: "sub-inqa",
            name: "In-Process Quality",
            sections: [
              {
                id: "sec-insp",
                name: "Visual & AOI Inspection",
                lines: [
                  {
                    id: "line-qa-1",
                    name: "Inspection Line 1",
                    processes: [
                      {
                        id: "proc-aoi",
                        name: "Automated Optical Inspection",
                        stations: [
                          {
                            id: "stn-aoi-01",
                            name: "Station 01 - AOI Scan",
                            machines: ["AOI Vision System 01", "3D Optical Scanner"],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "plant-2",
    name: "Plant 2 - Bawal",
    departments: [
      {
        id: "dept-prod-2",
        name: "Production",
        subDepartments: [
          {
            id: "sub-final-asm",
            name: "Final Assembly",
            sections: [
              {
                id: "sec-box",
                name: "Box Build & Enclosure",
                lines: [
                  {
                    id: "line-box-1",
                    name: "Line A",
                    processes: [
                      {
                        id: "proc-torque",
                        name: "Precision Torquing",
                        stations: [
                          {
                            id: "stn-torq-01",
                            name: "Station 01 - Screwdriving",
                            machines: ["Atlas Copco MicroTorque", "Desoutter D-02"],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 1,
    code: "CRS-ASM-001",
    title: "Connector Assembly Training",
    category: "Process Training",
    plant: "Plant 1 - Manesar",
    departmentId: 1,
    department: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 3",
    process: "Connector Assembly",
    machine: "Torque Machine 04",
    skillLevelFrom: "L1",
    skillLevelTo: "L2",
    durationMinutes: 45,
    modulesCount: 6,
    assessmentQuestions: 20,
    passingPercentage: 80,
    dojoRequired: true,
    mandatory: true,
    certificationRequired: true,
    validityMonths: 12,
    status: "Active",
    description: "Standard operating procedure for automotive multipin connector insertion, terminal locking, and click-sound confirmation.",
  },
  {
    id: 2,
    code: "CRS-CRMP-002",
    title: "Terminal Crimping Standard",
    category: "Process Training",
    plant: "Plant 1 - Manesar",
    departmentId: 1,
    department: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 3",
    process: "Terminal Crimping",
    machine: "Automatic Crimper C-12",
    skillLevelFrom: "L1",
    skillLevelTo: "L2",
    durationMinutes: 60,
    modulesCount: 8,
    assessmentQuestions: 25,
    passingPercentage: 85,
    dojoRequired: true,
    mandatory: true,
    certificationRequired: true,
    validityMonths: 12,
    status: "Active",
    description: "Crimping height, pull-test verification, and cross-section analysis for high reliability harnesses.",
  },
  {
    id: 3,
    code: "CRS-WELD-003",
    title: "Ultrasonic Splice Welding",
    category: "Equipment Training",
    plant: "Plant 1 - Manesar",
    departmentId: 1,
    department: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 1",
    process: "Ultrasonic Welding",
    machine: "Ultrasonic Welder U-02",
    skillLevelFrom: "L2",
    skillLevelTo: "L3",
    durationMinutes: 90,
    modulesCount: 10,
    assessmentQuestions: 30,
    passingPercentage: 85,
    dojoRequired: true,
    mandatory: false,
    certificationRequired: true,
    validityMonths: 24,
    status: "Active",
    description: "Horn calibration, energy settings, and tensile test procedures for copper wire splices.",
  },
  {
    id: 4,
    code: "CRS-QA-004",
    title: "AOI Defect Identification",
    category: "Quality Inspection",
    plant: "Plant 1 - Manesar",
    departmentId: 2,
    department: "Quality Control",
    subDepartment: "In-Process Quality",
    section: "Visual & AOI Inspection",
    line: "Inspection Line 1",
    process: "Automated Optical Inspection",
    machine: "AOI Vision System 01",
    skillLevelFrom: "L1",
    skillLevelTo: "L2",
    durationMinutes: 50,
    modulesCount: 5,
    assessmentQuestions: 15,
    passingPercentage: 90,
    dojoRequired: true,
    mandatory: true,
    certificationRequired: true,
    validityMonths: 12,
    status: "Active",
    description: "Defect taxonomy, false-call analysis, and IPC-A-610 visual acceptance criteria.",
  },
  {
    id: 5,
    code: "CRS-ESD-005",
    title: "ESD & Cleanroom Protocols",
    category: "Safety & Compliance",
    plant: "Plant 1 - Manesar",
    departmentId: 1,
    department: "Production",
    subDepartment: "PCB Fabrication",
    section: "SMT Section",
    line: "SMT Line 1",
    process: "Component Placement",
    machine: "Fuji NXT III",
    skillLevelFrom: "L0",
    skillLevelTo: "L1",
    durationMinutes: 30,
    modulesCount: 4,
    assessmentQuestions: 10,
    passingPercentage: 100,
    dojoRequired: false,
    mandatory: true,
    certificationRequired: false,
    validityMonths: 6,
    status: "Active",
    description: "Wrist strap grounding, ESD footwear testing, humidity monitoring, and clean handling.",
  },
  {
    id: 6,
    code: "CRS-SMT-006",
    title: "SMT Feeder Setup & Maintenance",
    category: "Machine Operation",
    plant: "Plant 1 - Manesar",
    departmentId: 1,
    department: "Production",
    subDepartment: "PCB Fabrication",
    section: "SMT Section",
    line: "SMT Line 1",
    process: "Component Placement",
    machine: "Fuji NXT III",
    skillLevelFrom: "L2",
    skillLevelTo: "L3",
    durationMinutes: 75,
    modulesCount: 7,
    assessmentQuestions: 20,
    passingPercentage: 80,
    dojoRequired: true,
    mandatory: false,
    certificationRequired: true,
    validityMonths: 18,
    status: "Under Review",
    description: "High speed tape splicing, reel barcode verification, and nozzle cleaning cycles.",
  },
  {
    id: 7,
    code: "CRS-TRQ-007",
    title: "Precision Torque Tightening",
    category: "Process Training",
    plant: "Plant 2 - Bawal",
    departmentId: 1,
    department: "Production",
    subDepartment: "Final Assembly",
    section: "Box Build & Enclosure",
    line: "Line A",
    process: "Precision Torquing",
    machine: "Atlas Copco MicroTorque",
    skillLevelFrom: "L1",
    skillLevelTo: "L2",
    durationMinutes: 40,
    modulesCount: 5,
    assessmentQuestions: 15,
    passingPercentage: 85,
    dojoRequired: true,
    mandatory: true,
    certificationRequired: true,
    validityMonths: 12,
    status: "Active",
    description: "Angle-controlled torquing, cross-pattern tightening, and tool batch-count verification.",
  },
  {
    id: 8,
    code: "CRS-CUT-008",
    title: "Automated Wire Cutting & Stripping",
    category: "Machine Operation",
    plant: "Plant 1 - Manesar",
    departmentId: 1,
    department: "Production",
    subDepartment: "Wiring Harness",
    section: "Cutting & Stripping",
    line: "Line 2",
    process: "High Speed Wire Cut",
    machine: "Komax Alpha 550",
    skillLevelFrom: "L1",
    skillLevelTo: "L2",
    durationMinutes: 60,
    modulesCount: 6,
    assessmentQuestions: 18,
    passingPercentage: 80,
    dojoRequired: true,
    mandatory: false,
    certificationRequired: false,
    validityMonths: 12,
    status: "Draft",
    description: "Blade changeover, strip length calibration, and zero-defect strand integrity check.",
  },
];

export const INITIAL_DOJO_TRAININGS: DojoTraining[] = [
  {
    id: 101,
    employeeId: "EMP001",
    employeeName: "Rahul Kumar",
    department: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 3",
    process: "Connector Assembly",
    machine: "Torque Machine 04",
    skillLevelFrom: "L1",
    skillLevelTo: "L2",
    trainingProgress: 100,
    practicalScore: 86,
    certificationStatus: "Certified",
    status: "Certified",
    trainerName: "Vikram Singh (Master Trainer)",
    supervisorName: "Sanjay Sharma",
    startDate: "2025-08-01",
    completionDate: "2025-08-14",
    certificateNumber: "DOJO-2025-0891",
    certificateIssuedDate: "2025-08-15",
    validTill: "2027-03-31",
    evaluationRemarks: "Demonstrated zero pin backouts in 200 consecutive test insertions. Excellent adherence to 5S.",
  },
  {
    id: 102,
    employeeId: "EMP002",
    employeeName: "Priya Sharma",
    department: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 3",
    process: "Terminal Crimping",
    machine: "Automatic Crimper C-12",
    skillLevelFrom: "L1",
    skillLevelTo: "L2",
    trainingProgress: 100,
    practicalScore: 92,
    certificationStatus: "Certified",
    status: "Certified",
    trainerName: "Vikram Singh (Master Trainer)",
    supervisorName: "Sanjay Sharma",
    startDate: "2025-07-10",
    completionDate: "2025-07-24",
    certificateNumber: "DOJO-2025-0744",
    certificateIssuedDate: "2025-07-25",
    validTill: "2027-04-30",
    evaluationRemarks: "Perfect pull test values across all wire gauges (0.5 to 2.5 mm²).",
  },
  {
    id: 103,
    employeeId: "EMP003",
    employeeName: "Amit Patel",
    department: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 1",
    process: "Ultrasonic Welding",
    machine: "Ultrasonic Welder U-02",
    skillLevelFrom: "L2",
    skillLevelTo: "L3",
    trainingProgress: 80,
    practicalScore: 78,
    certificationStatus: "Evaluation Pending",
    status: "Evaluation Pending",
    trainerName: "Manoj Verma (Lead Trainer)",
    supervisorName: "Rajesh Gupta",
    startDate: "2025-09-01",
    completionDate: "2025-09-18",
    validTill: "2026-09-18",
    evaluationRemarks: "Practical run completed. Second supervisor sign-off pending.",
  },
  {
    id: 104,
    employeeId: "EMP004",
    employeeName: "Sunita Verma",
    department: "Quality Control",
    subDepartment: "In-Process Quality",
    section: "Visual & AOI Inspection",
    line: "Inspection Line 1",
    process: "Automated Optical Inspection",
    machine: "AOI Vision System 01",
    skillLevelFrom: "L1",
    skillLevelTo: "L2",
    trainingProgress: 100,
    practicalScore: 95,
    certificationStatus: "Certified",
    status: "Certified",
    trainerName: "Anjali Saxena (QA Specialist)",
    supervisorName: "Deepak Mehra",
    startDate: "2025-06-05",
    completionDate: "2025-06-19",
    certificateNumber: "DOJO-2025-0612",
    certificateIssuedDate: "2025-06-20",
    validTill: "2026-06-20",
    evaluationRemarks: "Detected 100% seeded solder bridging and missing capacitor defects.",
  },
  {
    id: 105,
    employeeId: "EMP005",
    employeeName: "Rakesh Yadav",
    department: "Production",
    subDepartment: "PCB Fabrication",
    section: "SMT Section",
    line: "SMT Line 1",
    process: "Component Placement",
    machine: "Fuji NXT III",
    skillLevelFrom: "L2",
    skillLevelTo: "L3",
    trainingProgress: 55,
    practicalScore: 0,
    certificationStatus: "In Progress",
    status: "Training",
    trainerName: "Karthik R (SMT Expert)",
    supervisorName: "Sanjay Sharma",
    startDate: "2025-09-10",
    evaluationRemarks: "Undergoing module 4 hands-on feeder calibration and nozzle pitch setup.",
  },
  {
    id: 106,
    employeeId: "EMP006",
    employeeName: "Anil Deshmukh",
    department: "Production",
    subDepartment: "Wiring Harness",
    section: "Cutting & Stripping",
    line: "Line 2",
    process: "High Speed Wire Cut",
    machine: "Komax Alpha 550",
    skillLevelFrom: "L1",
    skillLevelTo: "L2",
    trainingProgress: 100,
    practicalScore: 62,
    certificationStatus: "Retraining Required",
    status: "Retraining Required",
    trainerName: "Vikram Singh (Master Trainer)",
    supervisorName: "Sanjay Sharma",
    startDate: "2025-08-15",
    completionDate: "2025-08-28",
    evaluationRemarks: "Cut length deviation observed on 0.75mm² PVC cables. Required 3-day retraining on wire tensioning.",
  },
  {
    id: 107,
    employeeId: "EMP007",
    employeeName: "Deepika Padukone",
    department: "Production",
    subDepartment: "Final Assembly",
    section: "Box Build & Enclosure",
    line: "Line A",
    process: "Precision Torquing",
    machine: "Atlas Copco MicroTorque",
    skillLevelFrom: "L1",
    skillLevelTo: "L2",
    trainingProgress: 100,
    practicalScore: 88,
    certificationStatus: "Certified",
    status: "Certified",
    trainerName: "Vikram Singh (Master Trainer)",
    supervisorName: "Rajesh Gupta",
    startDate: "2025-07-01",
    completionDate: "2025-07-15",
    certificateNumber: "DOJO-2025-0711",
    certificateIssuedDate: "2025-07-16",
    validTill: "2027-02-28",
    evaluationRemarks: "Strict torque angle adherence verified on critical fastener M4.",
  },
  {
    id: 108,
    employeeId: "EMP008",
    employeeName: "Gaurav Joshi",
    department: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 3",
    process: "Connector Assembly",
    machine: "Torque Machine 04",
    skillLevelFrom: "L1",
    skillLevelTo: "L2",
    trainingProgress: 100,
    practicalScore: 84,
    certificationStatus: "Expired",
    status: "Expired",
    trainerName: "Vikram Singh (Master Trainer)",
    supervisorName: "Sanjay Sharma",
    startDate: "2024-03-01",
    completionDate: "2024-03-15",
    certificateNumber: "DOJO-2024-0319",
    certificateIssuedDate: "2024-03-16",
    validTill: "2025-03-16",
    evaluationRemarks: "Certification validity passed 12-month tenure. Renewal evaluation scheduled.",
  },
  {
    id: 109,
    employeeId: "EMP009",
    employeeName: "Sneha Nair",
    department: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 1",
    process: "Ultrasonic Welding",
    machine: "Ultrasonic Welder U-02",
    skillLevelFrom: "L2",
    skillLevelTo: "L3",
    trainingProgress: 100,
    practicalScore: 90,
    certificationStatus: "Certified",
    status: "Certified",
    trainerName: "Manoj Verma (Lead Trainer)",
    supervisorName: "Rajesh Gupta",
    startDate: "2025-05-10",
    completionDate: "2025-05-24",
    certificateNumber: "DOJO-2025-0542",
    certificateIssuedDate: "2025-05-25",
    validTill: "2027-05-25",
    evaluationRemarks: "High qualification for high-voltage battery harness splices.",
  },
  {
    id: 110,
    employeeId: "EMP010",
    employeeName: "Mohan Lal",
    department: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 3",
    process: "Connector Assembly",
    machine: "Torque Machine 04",
    skillLevelFrom: "L1",
    skillLevelTo: "L2",
    trainingProgress: 20,
    practicalScore: 0,
    certificationStatus: "In Progress",
    status: "Assigned",
    trainerName: "Vikram Singh (Master Trainer)",
    supervisorName: "Sanjay Sharma",
    startDate: "2025-09-15",
    evaluationRemarks: "Initial theory passed, practical station allotment made.",
  },
];

export const INITIAL_OPERATOR_ASSIGNMENTS: OperatorAssignment[] = [
  {
    id: 201,
    operatorId: "EMP001",
    operatorName: "Rahul Kumar",
    certificationName: "DOJO Certified - Connector Assembly",
    processName: "Connector Assembly",
    skillLevel: "L3",
    plant: "Plant 1 - Manesar",
    currentDepartment: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 3",
    station: "Station 01 - Pin Insertion",
    machine: "Torque Machine 04",
    shift: "Shift A",
    assignmentStatus: "Assigned",
    assignmentType: "Permanent",
    validityDate: "31 Mar 2027",
    effectiveFrom: "2025-08-16",
    effectiveTo: "2026-08-16",
    remarks: "Lead operator for connector station. Zero defect track record.",
  },
  {
    id: 202,
    operatorId: "EMP002",
    operatorName: "Priya Sharma",
    certificationName: "DOJO Certified - Terminal Crimping",
    processName: "Terminal Crimping",
    skillLevel: "L2",
    plant: "Plant 1 - Manesar",
    currentDepartment: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 3",
    station: "Station 03 - Auto Crimp",
    machine: "Automatic Crimper C-12",
    shift: "Shift A",
    assignmentStatus: "Assigned",
    assignmentType: "Permanent",
    validityDate: "30 Apr 2027",
    effectiveFrom: "2025-07-26",
    effectiveTo: "2026-07-26",
    remarks: "Assigned to high-speed crimping line.",
  },
  {
    id: 203,
    operatorId: "EMP004",
    operatorName: "Sunita Verma",
    certificationName: "DOJO Certified - AOI Defect Inspection",
    processName: "Automated Optical Inspection",
    skillLevel: "L2",
    plant: "Plant 1 - Manesar",
    currentDepartment: "Quality Control",
    subDepartment: "In-Process Quality",
    section: "Visual & AOI Inspection",
    line: "Inspection Line 1",
    station: "Station 01 - AOI Scan",
    machine: "AOI Vision System 01",
    shift: "Shift B",
    assignmentStatus: "Certification Expiring",
    assignmentType: "Permanent",
    validityDate: "20 Oct 2025",
    effectiveFrom: "2024-10-20",
    effectiveTo: "2025-10-20",
    remarks: "Certification expiring in under 30 days. Recertification DOJO session requested.",
  },
  {
    id: 204,
    operatorId: "EMP007",
    operatorName: "Deepika Padukone",
    certificationName: "DOJO Certified - Precision Torquing",
    processName: "Precision Torquing",
    skillLevel: "L2",
    plant: "Plant 2 - Bawal",
    currentDepartment: "Production",
    subDepartment: "Final Assembly",
    section: "Box Build & Enclosure",
    line: "Line A",
    station: "Station 01 - Screwdriving",
    machine: "Atlas Copco MicroTorque",
    shift: "Shift A",
    assignmentStatus: "Assigned",
    assignmentType: "Job Rotation",
    validityDate: "28 Feb 2027",
    effectiveFrom: "2025-08-01",
    effectiveTo: "2025-11-01",
    remarks: "3-month job rotation deployment from Plant 1.",
  },
  {
    id: 205,
    operatorId: "EMP009",
    operatorName: "Sneha Nair",
    certificationName: "DOJO Certified - Ultrasonic Welding",
    processName: "Ultrasonic Welding",
    skillLevel: "L3",
    plant: "Plant 1 - Manesar",
    currentDepartment: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 1",
    station: "Station 01 - Splice Weld",
    machine: "Ultrasonic Welder U-02",
    shift: "Shift C",
    assignmentStatus: "Available",
    assignmentType: "Backup",
    validityDate: "25 May 2027",
    effectiveFrom: "2025-06-01",
    effectiveTo: "2026-06-01",
    remarks: "Ready on standby for critical night-shift battery pack harness.",
  },
  {
    id: 206,
    operatorId: "EMP008",
    operatorName: "Gaurav Joshi",
    certificationName: "DOJO Certified - Connector Assembly",
    processName: "Connector Assembly",
    skillLevel: "L2",
    plant: "Plant 1 - Manesar",
    currentDepartment: "Production",
    subDepartment: "Wiring Harness",
    section: "Assembly",
    line: "Line 3",
    station: "Station 01 - Pin Insertion",
    machine: "Torque Machine 04",
    shift: "Shift General",
    assignmentStatus: "Expired",
    assignmentType: "Temporary",
    validityDate: "16 Mar 2025",
    effectiveFrom: "2024-04-01",
    effectiveTo: "2025-03-16",
    remarks: "DOJO certification has expired. Cannot operate until retrained.",
  },
  {
    id: 207,
    operatorId: "EMP011",
    operatorName: "Rohan Kulkarni",
    certificationName: "DOJO Certified - Wire Cutting & Stripping",
    processName: "High Speed Wire Cut",
    skillLevel: "L3",
    plant: "Plant 1 - Manesar",
    currentDepartment: "Production",
    subDepartment: "Wiring Harness",
    section: "Cutting & Stripping",
    line: "Line 2",
    station: "Station 01 - Feeder Cut",
    machine: "Komax Alpha 550",
    shift: "Shift A",
    assignmentStatus: "Available",
    assignmentType: "Permanent",
    validityDate: "15 Dec 2026",
    effectiveFrom: "2025-01-01",
    effectiveTo: "2026-01-01",
    remarks: "Available for reallocation or second line support.",
  },
  {
    id: 208,
    operatorId: "EMP012",
    operatorName: "Pooja Hegde",
    certificationName: "DOJO Certified - Precision Torquing",
    processName: "Precision Torquing",
    skillLevel: "L2",
    plant: "Plant 2 - Bawal",
    currentDepartment: "Production",
    subDepartment: "Final Assembly",
    section: "Box Build & Enclosure",
    line: "Line A",
    station: "Station 01 - Screwdriving",
    machine: "Atlas Copco MicroTorque",
    shift: "Shift B",
    assignmentStatus: "Assigned",
    assignmentType: "Permanent",
    validityDate: "14 Jul 2026",
    effectiveFrom: "2025-02-15",
    effectiveTo: "2026-02-15",
    remarks: "Assigned to second shift enclosure torquing cell.",
  },
];

export const CERTIFIED_OPERATOR_OPTIONS = [
  {
    operatorId: "EMP001",
    operatorName: "Rahul Kumar",
    certification: "DOJO Certified - Connector Assembly",
    skillLevel: "L3",
    process: "Connector Assembly",
    validTill: "31 Mar 2027",
  },
  {
    operatorId: "EMP002",
    operatorName: "Priya Sharma",
    certification: "DOJO Certified - Terminal Crimping",
    skillLevel: "L2",
    process: "Terminal Crimping",
    validTill: "30 Apr 2027",
  },
  {
    operatorId: "EMP004",
    operatorName: "Sunita Verma",
    certification: "DOJO Certified - AOI Defect Inspection",
    skillLevel: "L2",
    process: "Automated Optical Inspection",
    validTill: "20 Oct 2025",
  },
  {
    operatorId: "EMP007",
    operatorName: "Deepika Padukone",
    certification: "DOJO Certified - Precision Torquing",
    skillLevel: "L2",
    process: "Precision Torquing",
    validTill: "28 Feb 2027",
  },
  {
    operatorId: "EMP009",
    operatorName: "Sneha Nair",
    certification: "DOJO Certified - Ultrasonic Welding",
    skillLevel: "L3",
    process: "Ultrasonic Welding",
    validTill: "25 May 2027",
  },
  {
    operatorId: "EMP011",
    operatorName: "Rohan Kulkarni",
    certification: "DOJO Certified - Wire Cutting & Stripping",
    skillLevel: "L3",
    process: "High Speed Wire Cut",
    validTill: "15 Dec 2026",
  },
  {
    operatorId: "EMP012",
    operatorName: "Pooja Hegde",
    certification: "DOJO Certified - Precision Torquing",
    skillLevel: "L2",
    process: "Precision Torquing",
    validTill: "14 Jul 2026",
  },
];
